version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test-cloud
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_crawler
      timeout: 300
      runas: root

